# Site settings
title: Just a small corner
email: smilekid1994@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hạnh phúc là con đường chứ không phải đích đến.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://smilekid1994.github.io" # the base hostname & protocol for your site
github_username:  smilekid1994

# Build settings
markdown: redcarpet
